### ISSUE TITLE
Hardcoded Ethprice in prices.js

### ISSUE THREAD

**Issue by Devilla** [Devilla/eth-arbitrage-2#3]
# Issue

Remove or replace hardcoded eth price (i.e. "1800") with commented code in front of the value.

# Snapshot

![image (3)](https://github.com/Devilla/eth-arbitrage-2/assets/15603274/b7a9206b-eb43-4876-87d4-7ebecbcda380)

**Comment by Yassinst2** [comment]
> # Issue
> Remove or replace hardcoded eth price (i.e. "1800") with commented code in front of the value.
> 
> # Snapshot
> ![image](https://user-images.githubusercontent.com/15603274/242208548-7502ff31-f9ef-425e-9fb1-e1585fc08906.png)
the image do not appear

**Comment by Devilla** [comment]
> > # Issue
> > Remove or replace hardcoded eth price (i.e. "1800") with commented code in front of the value.
> > # Snapshot
> > ![image](https://user-images.githubusercontent.com/15603274/242208548-7502ff31-f9ef-425e-9fb1-e1585fc08906.png)
> > the image do not appear

Yes, I think it's solved now.
