### ISSUE TITLE
ERROR!!!

### ISSUE THREAD

**Issue by Han-GK** [Devilla/eth-arbitrage-2#9]
ERROR in ./node_modules/web3-providers-http/lib/index.js 26:11-26
Module not found: Error: Can't resolve 'http' in '/home/hanguokun/eth-arbitrage-2/node_modules/web3-providers-http/lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "http": require.resolve("stream-http") }'
        - install 'stream-http'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "http": false }

ERROR in ./node_modules/web3-providers-http/lib/index.js 27:12-28
Module not found: Error: Can't resolve 'https' in '/home/hanguokun/eth-arbitrage-2/node_modules/web3-providers-http/lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "https": require.resolve("https-browserify") }'
        - install 'https-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "https": false }

webpack compiled with 2 errors and 60 warnings

**Comment by Devilla** [comment]
Install the required dependencies i.e. `http`, `https` etc.

**Comment by doldsimo** [comment]
@Devilla  I have the same problem, installing does not fix the problem.

@Han-GK did you found a solution?
